SELECT TOP (1000) [LoanAccountBalanceId]
      ,[SourceId]
      ,[BalanceDateId]
      ,[LoanAccountId]
      ,[ProductId]
      ,[AccountCurrencyId]
      ,[AccountStatusId]
      ,[NumOfTransactions]
      ,[NetTransactionAmount]
      ,[NetTransactionAmountSek]
      ,[AccruedInterest]
      ,[AccruedInterestSEK]
      ,[Balance]
      ,[BalanceSek]
      ,[LTV]
      ,[PrecedingId]
  FROM [ETL_Assignment2].[cleansed].[Loan_Account_Balance]
